### ISSUE TITLE
Раунд с Tau Ceti I не отображается.

### ISSUE THREAD

**Issue by BirgusL** [KIBORG04/ProjectTau#2]
Не отображается раунд с 17:06 по 20:32 19/05/2023. Попытался найти ещё такой прецендент, но он, вроде, единственный.

**Comment by KIBORG04** [comment]
Жесть, мой гитхаб жив, но я кажется опоздал и это не актуально, да еще и ид раунда не указано. Ну, в общем. пофиг

**Comment by BirgusL** [comment]
ID раунда не мог сказать, так как раунд в принципе не отображался. Где
можно взять Id в клиенте?

вт, 10 окт. 2023 г., 02:24 KIBORG04 ***@***.***>:
